### ISSUE TITLE
Entire system freezes while reproducing music through bonob

### ISSUE THREAD

**Issue by garret** [simojenki/bonob#102]
I installed bonob on a raspberry pi 4 through a docker container (arm64). It has been working fine for several months but today it is second time in a period of around 2-3 weeks that it crashes. While I am reproducing music from my sonos app, I get at some point an error message in the app while I am scrolling through my library saying that this sons cannot be reproduced or something similar. The error starts to appear many times as a notification in the sonos app. At the same time, the raspberry pi freezes. So much that I cannot access heedlessly through ssh. I have to connect it to a monitor and then use the keyboard to login to the terminal. Even logging in takes around 10 min and the first thing I do is a "sudo reboot" to avoid the cold unplugging/re-plugging the power. Do you know what could be the issue? It is difficult to see any logs since, as described before, the system freezes entirely.

**Comment by simojenki** [comment]
Does this happen when you are scrolling rapidly through a list (ie 'Artists' list)?

Are you using Navidrome as a source?

**Comment by garret** [comment]
I am using Navidrome as source (also this installed on the same rpi4 via docker) I think the first time it might have happened when I was scrolling through the lists of artists coming from the "Random" tab in the sonos app. The second time was when I was looking through the sonos app at an album which only contained two songs. The first song was almost over and I pressed manually to start the second song. However, it soon started to show several times this error notification inside the sonos app that could not find/reproduce the song and at the same time the rpi4 completely freezes. It took me almost 15 min just to login through the keyboard attached to the rpi4.

**Comment by simojenki** [comment]
That's interesting.

I think what happens is that requests between Sonos controller & bonob start taking too long, which confuses the Sonos controller.

I have received similar behaviour when scrolling through lists very quickly.   In my case I increased the amount of memory I allocate to the Navidrome container, which seemed to increase its' performance, which has removed the issue.

If you could try and get some logs next time, that might help diagnose.

**Comment by garret** [comment]
Could you suggest me an easy shell command that, after I physically log into the rpi4 (ssh as said before does not work anymore), I can give to save a copy of the log and then give the "sudo reboot" command right after? I have dozzle and portainer installed on that rpi4 but when the rpi4 freezes they don't respond anymore. So I have to find an easy solution because it seems like the rpi4 cpu jumps to 100% when this issue happens.

**Comment by simojenki** [comment]
When you create the container, perhaps give it a name, ie. 'bonob'

The something like the following should dump the logs.
```
docker logs [container name]
```

Given the CPU is hitting 100% you should also use 'top' to try and work out which process is using all that CPU.

**Comment by garret** [comment]
Hi today it happened again. I went to the "Random" tab on Bonob and selected a song. When the song finished I went back to the "Random" view showing random albums. I tapped on an album containing only one song and then on the song. Soon I received a notification error on the bottom part of my phone. Again the raspberry pi 4 freezed completely. However, I noticed this time that after around 20 minutes it unfreezed by itself. I can attach both the logs from bonob and navidrome. The issue happened at around 18:50 and it unfreezed around 19:12. Please let me know if there are sensitive information I should cover. 

Navidrome log:
```
yesterday at 18:38:09time="2022-04-20T16:38:09Z" level=info msg="Now Playing" artist=Hooverphonic player="bonob [bonob]" title=Romantic user=garret
yesterday at 18:41:28time="2022-04-20T16:41:28Z" level=info msg=Scrobbled artist=Hooverphonic timestamp="2022-04-20 16:41:28.346695294 +0000 UTC m=+253070.129267233" title=Romantic user=garret
today at 18:46:19time="2022-04-21T16:46:19Z" level=info msg="Streaming file" artist="Marvin Berry and the Starlighters" bitRate=0 cached=false format=raw originalBitRate=711 originalFormat=flac title="Earth Angel (Will You Be Mine)" transcoding=false user=garret
today at 18:46:19time="2022-04-21T16:46:19Z" level=info msg="Now Playing" artist="Marvin Berry and the Starlighters" player="bonob [bonob]" title="Earth Angel (Will You Be Mine)" user=garret
today at 18:49:25time="2022-04-21T16:49:25Z" level=info msg=Scrobbled artist="Marvin Berry and the Starlighters" timestamp="2022-04-21 16:49:25.765711592 +0000 UTC m=+339947.548283568" title="Earth Angel (Will You Be Mine)" user=garret
today at 19:14:51time="2022-04-21T17:14:51Z" level=warning msg="HTTP: GET http://10.10.10.10:4533/api/playlist?_end=0&_sort=name&_start=-100" elapsedTime=2.2ms httpStatus=401 remoteAddr="10.10.10.3:50461" requestId=2d002e8998b9/vIrM0siDkv-012172 responseSize=29
today at 19:14:51time="2022-04-21T17:14:51Z" level=warning msg="HTTP: GET http://10.10.10.10:4533/api/album?_end=18&_order=DESC&_sort=play_count&_start=0&recently_played=true" elapsedTime=1.8ms httpStatus=401 remoteAddr="10.10.10.3:50461" requestId=2d002e8
[bonob_log.txt](https://github.com/simojenki/bonob/files/8533259/bonob_log.txt)
998b9/vIrM0siDkv-012173 responseSize=29
today at 19:14:51time="2022-04-21T17:14:51Z" level=warning msg="HTTP: GET http://10.10.10.10:4533/api/keepalive/keepalive" elapsedTime="393.792µs" httpStatus=401 remoteAddr="10.10.10.3:50461" requestId=2d002e8998b9/vIrM0siDkv-012174 responseSize=29
```

**Comment by simojenki** [comment]
There is nothing obvious in the log.

It is likely frozen because the CPU is hitting 100% doing something, after an amount of time (20 min in this case) it seems that the CPU has spare cycles and the Pi is working again.

How much memory have you allocated to both bonob and navidrome?  Try increasing it for both and see what happens?

**Comment by garret** [comment]
I don't know how much memory I have allocated to both as I am using the standard docker-compose setup for both applications. Do you have any recommendations on how to do it through docker-compose and what value to use considering I have a raspberry pi 4 with 4GB of ram (running aarch64).

**Comment by simojenki** [comment]
I don't use docker-compose myself, I just provided that file as an example.  Personally I just start the containers individually, and specify the memory explicitly for each.

I'll try and find my own RPi and test it on that.

**Comment by garret** [comment]
Thank you very much. I will wait for your test then.

**Comment by garret** [comment]
I think I might have understood what was the issue. I had installed telegraf(local) + influxdb(docker) + grafana(docker) on the same raspberry pi running  bonob(docker). I can see that after stopping the influxdb and grafana containers, the rpi does not freeze anymore after running bonob for some time. My feeling is that influxdb was receiving an enormous amount of data from telegraf when bonob was running for some time, freezing the system. I will close the issue and eventually re-open it if it happens again. Thank you for the support in the meanwhile.

**Comment by simojenki** [comment]
Great, I'm glad it is working for you now.
I guess the RPi can run out of resources if too many things are running. Great little machines though.
