### ISSUE TITLE
No playlists available in bonob

### ISSUE THREAD

**Issue by flvinny521** [simojenki/bonob#104]
Hello, thanks for your work on this project. I have Navidrome set up and bonob is added to my Sonos app as a service. I can play all available music without issue, but my 20+ playlists do not appear in Sonos. These playlists are available on the Navidrome web interface as well as the DSub app. I tried removing bonob and reauthorizing it, hoping to refresh the playlists, but this was unsuccessful. Any thoughts?

**Comment by simojenki** [comment]
that is odd, i have a number of playlists in ND and I can see them all in bonob/sonos.   Is there anything in the bonob log that might give some clues?

**Comment by simojenki** [comment]
The bonob logs should be a good place to start, there should be a message something like

`{"message":"Fetching metadata type=playlists`

and then the right after it something like;

`{"message":{"level":"debug","data":"<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"  xmlns:tns=\"http://www.sonos.com/Services/1.1\"><soap:Body><getMetadataResponse xmlns=\"http://www.sonos.com/Services/1.1\"><getMetadataResult><count>10</count><index>0</index><total>10</total><mediaCollection readOnly=\"false\" userContent=\"false\" renameable=\"false\"><itemType>playlist</itemType>.................`

**Comment by flvinny521** [comment]
Sorry for the long delay. I had somewhat forgotten about this until I was poking around in Navidrome today for an unrelated issue.  I noticed that I had neglected to set the playlists to "public," and since I was logging in to bonob using an account other than the amin, that is why those playlists were not available to me.
