### ISSUE TITLE
Strange uri when not using network host (use docker container id instead of IP)

### ISSUE THREAD

**Issue by ygbillet** [simojenki/bonob#11]
Starting Bonob with Docker

    $ sudo docker run -d  --name=bonob   \
                    -e BONOB_SONOS_SERVICE_NAME=navidrome \
                    -e BONOB_SONOS_AUTO_REGISTER=true  \
                    -e BONOB_WEB_ADRESS=http://192.168.1.23:4534 \
                    -e BONOB_SONOS_SEED_HOST=192.168.1.5 \
                    -e BONOB_NAVIDROME_URL=http://192.168.1.23 \
                    -p 4534:4534 \
                    simojenki/bonob
    
    e6176817ca2a5062952de977f26f4fa9ff88dc0bbf13e889fed98a8f01c58d7c

What i see in web interface (192.168.1.23:4534)

> {"name":"navidrome","sid":246,"uri":"http://e6176817ca2a:4534/ws/sonos","secureUri":"http://e6176817ca2a:4534/ws/sonos","strings":{"uri":"http://e6176817ca2a:4534/sonos/strings.xml","version":"18"},"presentation":{"uri":"http://e6176817ca2a:4534/sonos/presentationMap.xml","version":"18"},"pollInterval":1200,"authType":"AppLink"}

**Comment by simojenki** [comment]
mm, this seems strange.  I'm making some changes in this space to support running bonob under a context path, so I'll verify this behaviour at the same time,

**Comment by simojenki** [comment]
You have a typo in 'BONOB_WEB_ADRESS', missing a 'D'.

Note that in the latest build I renamed BONOB_WEB_ADDRESS to BONOB_URL.  BONOB_WEB_ADDRESS will continue to work for now.
