### ISSUE TITLE
Trouble scrobbling

### ISSUE THREAD

**Issue by andrasbarany** [simojenki/bonob#132]
I am using navidrome and bonob to listen to music on a set of SONOS speakers. Thanks for this great piece of software!

I have one issue: when using the navidrome web interface, scrobbling to last.fm and Listenbrainz works fine. When using listening on the SONOS speakers through bonob, I can see the currently playing song on last.fm and Listenbrainz, but it is not scrobbled.

I am launching bonob as follows:

```
/usr/bin/docker run -e BNB_SONOS_AUTO_REGISTER=true -e BNB_SONOS_DEVICE_DISCOVERY=true -e BNB_SONOS_SERVICE_NAME=X1 -e BNB_URL=http://192.168.0.210:4534 -e BNB_SUBSONIC_URL=http://192.168.0.210:4533 -e BNB_SCROBBLE_TRACKS=true -e -BNB_REPORT_NOW_PLAYING=true -p 4534:4534 --network host simojenki/bonob
```

I've tried with and without `BNB_SCROBBLE_TRACKS` and `BNB_REPORT_NOW_PLAYING` but there is no difference. Am I missing an option? Are there any logs I can access?

**Comment by simojenki** [comment]
What happens if you let the track run to its conclusion, does it scrobble then?

**Comment by andrasbarany** [comment]
I'm not sure what changed but it appears to be working as intended now.
