### ISSUE TITLE
Multiple registrations within a single household

### ISSUE THREAD

**Issue by dlehammer** [simojenki/bonob#139]
Hi bonob gurus,

The [features](https://github.com/simojenki/bonob/blob/4a529b46e1c09c9d1ca465677508cb5246d5c997/README.md#features) list includes:

>  - Multiple registrations within a single household

But I seem unable to figure how, based on the current documentation

Thanks in advance 🤓

**Comment by simojenki** [comment]
This is done via the Sonos app.  You simply re-register the service with the Sonos app, logging in with a different account.

I've only treated this on iOS, presumably it's the same on Android.
