### ISSUE TITLE
Wrong name when connecting to service

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#14]
Hi,

When you use a custom name for bonob you will still see bonob as the name of the service when you're connecting with Sonos.

This probably says it all:

![IMG_4134](https://user-images.githubusercontent.com/610740/128171133-1cce21c1-3b62-46fd-9aa5-dc6b3e478573.PNG)

On other screens I see "musicbox", as expected.

**Comment by jicho** [comment]
Just discovered on another device, where I did a first time connect with bonob, that de "linking with sonos" displayed the correct name...

Can the screenshots above be a the result of the Sonos App missing the updated name somewhere, or maybe caching?

**Comment by simojenki** [comment]
I think this should be fixed once the localisation is demonstrated to work.

**Comment by jicho** [comment]
Lets double check when the localization is playing along, for what I've seen it works now.

**Comment by jicho** [comment]
This one works with the latest version!
