### ISSUE TITLE
Provide alternate image registry to Docker Hub

### ISSUE THREAD

**Issue by bjw-s** [simojenki/bonob#152]
Since Docker Hub has been applying rate limits on image pulls for a while now, and their more recent move to scrap free teams I feel that Docker Hub is becoming more and more hostile towards the OSS/hobbyist community.

I would like to propose providing GitHub Container Registry as an alternative (or completely switching over to it) for the project.

Would you be open to this? If so, I'd be willing to write up a PR to implement.

**Comment by simojenki** [comment]
Yes, I also read about this and think this would be a good move.

**Comment by bjw-s** [comment]
I've created a PR that should (if all goes well 😄) push the image to GHCR in addition to Docker Hub
