### ISSUE TITLE
Pulling latest image results in error

### ISSUE THREAD

**Issue by stefan1983** [simojenki/bonob#154]
`root@server:~# docker pull docker.io/simojenki/bonob`

`Using default tag: latest`

`Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"`

`root@server:~# `

**Comment by simojenki** [comment]
I have just successfully pulled this image.

Do you see the same problem with ghcr? 
ie. 
```bash
docker pull ghcr.io/simojenki/bonob
```

**Comment by stefan1983** [comment]
Hmm..., today it seems to work again. Strange...

The ghcr.io link worked yesterday, I used that instead after docker.io didn't work for me.
