### ISSUE TITLE
ignore self signed certificate

### ISSUE THREAD

**Issue by djusHa** [simojenki/bonob#157]
Good Day,

nice Project!

Please add a possibility to ignore self signed certificate Errors.

Have running my gonic server behind a reverse proxy, with a self signed certificate, so on connect bonob says "cannot prove first certificate" or somethin.

**Comment by simojenki** [comment]
What happens if you set this env var on the process/container?

NODE_TLS_REJECT_UNAUTHORIZED=0

This is not a great solution, a better one needs to be found, however this may get you working again in the meantime.

**Comment by djusHa** [comment]
It works!

Set it as env on the docker container.

Thank you 👍
