### ISSUE TITLE
Issue loading large number of playlists

### ISSUE THREAD

**Issue by Vorror** [simojenki/bonob#158]
Bonob seems to have issues loading the "playlists" section of the Sonos controller app.
If I have a small number of playlists (< 20), then bonob/Sonos controller will correctly and quickly load all of the playlists.

![image](https://user-images.githubusercontent.com/3613230/232670920-8a92d442-ba53-4353-a7b7-b39c74f48163.png)

Unfortunately, I have 200 (smart) playlists. Sometimes, only the first 40 or so will load. The majority of the time, either Sonos or Bonob will time-out/give up retrieving the account's playlist and either show a blank page or only shows a small portion of the available playlists.

The issue may be because bonob is trying to retrieve the playlist album art for every playlist.

Can I disable album arts for the playlist section/folder?

**Comment by simojenki** [comment]
Yes, it could be beside it's too busy generating album art.

Given that ND now supports playlist artwork perhaps this feature should be disabled for ND

**Comment by Vorror** [comment]
> Yes, it could be beside it's too busy generating album art.
> 
> Given that ND now supports playlist artwork perhaps this feature should be disabled for ND

Thanks for the quick reply. Yes, that's my feeling based on watching the logs of bonob and noticing how slow the album art-related messages seem to pass.

**Comment by simojenki** [comment]
I've added a config param BNB_DISABLE_PLAYLIST_ART and released a new version, try setting this to "true" and it should disable album art and just show an icon.
When I have some time I'll come up with a better solution that uses ND for the playlist art now that it supports it.

**Comment by Vorror** [comment]
Thanks! I just tried the setting, and playlists load much faster!

**Comment by dhalem** [comment]
I tried it as well and they are still loading slowly.

**Comment by simojenki** [comment]
Still loading with images disabled?  How many playlists?  
Which backend type? 
How does the API of the backend itself perform?

With images disabled bonob really doesn't do much other than transform the subsonic api into something that Sonos understands so it's quite likely that the performance issue is elsewhere.

**Comment by dhalem** [comment]
The backed in ND, and I have ~800 playlists.  It looks like the lag is on the ND side, but it also appears that bonob is pulling the full set of 800 on each request.  I'm still poking around trying to see how pagination works.

**Comment by dhalem** [comment]
I see ND trying to load album art in its logs right now.

**Comment by dhalem** [comment]
I also see lots of individual calls to getPlaylist in the ND logs.

**Comment by simojenki** [comment]
Yes, still loads each playlist for the tracks, which on 800 is going to be very slow...
I'll look at fixing that.

**Comment by simojenki** [comment]
Out of interest, how are you managing 800 playlists?  That's a lot of playlists to be individually adding tracks to.

**Comment by dhalem** [comment]
That’s a longer story.  I have a home built system that syncs them from various sources (Spotify, Tidal, Plex, etc) then matches up tracks across those and pushes them back to the same services as well as exporting them as file system artifacts that Sonos and Navidrome can read.

**Comment by dhalem** [comment]
Does it need to get all the tracks during the listing phase?  Seems like it can operate on a shallower set of data.

**Comment by simojenki** [comment]
No, not any more. It did that because ND did not support album art for playlists, so bonob generated it from the playlist tracks.  However now that ND supports the same functionality natively it can be removed.

I hadn't imagined that people would have 800 odd playlists

**Comment by dhalem** [comment]
Thanks.  I think I understand the code enough to fix it.

**Comment by simojenki** [comment]
Go for it, I'm extremely busy right now with other things, so if you can send me a PR that would be great.

You could re-use the same config param i added in the most recent commit to master to disable loading the tracks for the playlists?

**Comment by dhalem** [comment]
I’m the opposite.  Retired

**Comment by dhalem** [comment]
PR sent

**Comment by simojenki** [comment]
PR merged.  That 'master' tagged docker image should contain this change.  Let me know how it goes, if its good, ill tag and release.

**Comment by Vorror** [comment]
@dhalem Did you validate your changes?

**Comment by dhalem** [comment]
Ah yes. I did.  Apologies.

**Comment by Vorror** [comment]
@simojenki I guess you can tag/release? I'll test the version that's uploaded. If everything things ends up okay Ill close the ticket.

**Comment by Vorror** [comment]
After running with @dhalem getting playlists is really fast now. Good work!

Closing.

**Comment by simojenki** [comment]
This is released, sorry was moving house, so hadn't had time.
