### ISSUE TITLE
Can't login to navidrome anymore. Bearer token problem.

### ISSUE THREAD

**Issue by dbuttric** [simojenki/bonob#177]
Sometime this evening, I started getting this error when I try to connect to the navidrome library through bonob usinng the sonos app:
Login failed!
Failed to get bearerToken

I tried looking in the open issues to see if there was a simple solution to this, but I didn't find anything.

What are some troubleshooting steps I can take?
In the logs there is just this message:
bonob_1      | {"level":"info","message":"Client not linked, awaiting user to associate account with link code by logging in.","service":"bonob","timestamp":"2023-10-11 00:50:45"}

in navidrome:
navidrome_1  | time="2023-10-11T02:02:11Z" level=warning msg="HTTP: POST http://jack2:4533//auth/login" elapsedTime="34.57µs" httpStatus=405 remoteAddr="172.23.0.1:58720" requestId=d67da29ae5e9/kT9uItsXYn-000008 responseSize=0

Thank you.
David

**Comment by simojenki** [comment]
Sorry, I accidentally broke it yesterday...have applied a fix and added a better test case...

**Comment by dbuttric** [comment]
The only issue left here is that 0.6.11 is not tagged as latest.
Other than that, this problem is fixed!

Thanks!

**Comment by dbuttric** [comment]
The only issue left here is that 0.6.11 is not tagged as latest.
Other than that, this problem is fixed!

Thanks!
