### ISSUE TITLE
Getting error tryingi to play song from navidrome

### ISSUE THREAD

**Issue by rayzorben** [simojenki/bonob#198]
Getting error `Unable to play Miles From Nowhere' - it is encoded at unsupported sample rate 24b192000 Hz.

Any idea what to do?

**Comment by simojenki** [comment]
Sonos will not play a 192kHz track, you need to down sample it to a supported format.  See the transcoding instructions.

**Comment by rayzorben** [comment]
Thanks, I thought so but I am really confused. I added the custom client and it shows up in navidrome but I cannot add a transcoding to navidrome. For the new player it allows me to select aac/mp3/opus but I can't add the new `ffmpeg -i %s -af aformat=sample_fmts=s16|s32:sample_rates=8000|11025|16000|22050|24000|32000|44100|48000 -f flac -`

**Comment by simojenki** [comment]
You need to add a transcoding with that command, and then assign the transcoding to the new player.

**Comment by rayzorben** [comment]
Ya I just figured out this is a navidrome issue I know, but you have to explicitly allow adding transcodings with an environment variable. Guess a toggle flag in the settings is too diffficult.

**Comment by simojenki** [comment]
I believe that it is like that on purpose for security reasons.  

ie. stops someone replacing your transcoding config with "rm -Rf /".  Then the next time you play a song your system gets wiped out.

**Comment by rayzorben** [comment]
Are there use cases where people are allowing other people to access their navidrome instance? 

either way seems like something that could be handled with permissions, one admin account, one normal account
