### ISSUE TITLE
Albums are sorted by artists, not by album title

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#20]
Hi,

Is it me, or is the sorting of the album incorrect?
When you request the list the albums are sorted by artist and under the artist by album...
I would expect everything be sorted by album title when I choose "album", just as it is done in Navidrome.

It this something that can be changed?
It feels like a (strong word) bug, but I have no idea if it is a limitation by Sonos, Navidrome or by design...?

**Comment by simojenki** [comment]
The order is the same as provided by Navidrome, which appears to be year.

**Comment by jicho** [comment]
Hmmm... that's strange... When I go to Navidrome (GUI) and I go to "All" I see all albums sorted by their name.

Or is the API(?) endpoint different for bonob different compared to the GUI one?

**Comment by jicho** [comment]
Just looked at Navidrome, when clicking on "all" you get the album list as I would expect to see in the Sonos App when choosing albums based on bonob.

The result for "all" in Navidrome is this request:
> http://navidrome/api/album?_end=18&_order=ASC&_sort=name&_start=0

I expect that bonob is calling ```/rest``` and so the subsonic API. The call with the following options:
> http://navidrome/rest/getAlbumList?u=xxxxxx&p=xxxxx&v=1.16.1&c=example&type=alphabeticalByName 

Is resulting in the same album list. 
Found it in the subsonic docs: http://www.subsonic.org/pages/api.jsp#getAlbumList
And based on that docs is seems that you are required to give a "type", without it you're not getting any albums.

Is it an idea to make the album list sorting in bonob something that can be configured? I'm only talking about the "albums" button.

**Comment by simojenki** [comment]
Ahh I see, TBH I don't use that view, though I think for consistency it should probably match what happens in the Navidrome UI.  I'll change it to match.

**Comment by simojenki** [comment]
Latest should fix this issue.

**Comment by jicho** [comment]
This one fixed indeed, thanks!
