### ISSUE TITLE
Question / Add years containers and albums display

### ISSUE THREAD

**Issue by jnth** [simojenki/bonob#201]
Hello,

First, thank you for this brilliant software!
I'm currently adding a new menu at the root level `Years` to show all years from album release dates. And after selecting a year, we can see all albums in order to play them.

![2](https://github.com/simojenki/bonob/assets/7796167/61417dc4-ad91-4174-bbb4-cd81d7722057)

![3](https://github.com/simojenki/bonob/assets/7796167/c72fe445-066c-447e-8e43-6bf7be8852bb)

It's working fine and I'll made a PR. But, as you can see at the screenshot, it's only show the album title. It's not like the favorite album menu that display the album title and the artist name.

I'm following the same way for this new menu like the other but I didn't find a difference...
Do you have any advice to show the album title and the artist name ?

**Comment by simojenki** [comment]
I think this might be determined by the itemType attribute.

Try making each year range have
itemType: "albumList",

**Comment by jnth** [comment]
Thank you for your advice. It fixes my problem.

I made a PR #202
