### ISSUE TITLE
Raspberry Pi Model B - ARMv6

### ISSUE THREAD

**Issue by pinknoise** [simojenki/bonob#206]
Question rather than an issue. I've searched high and low for an answer elsewhere.

At bonob Pulling I get the response:

`no matching manifest for linux/arm/v6 in the manifest list entries`

Should I assume that ARMv6 is not supported? Can anything be done about that? I'm running the latest RPi OS Lite 32-bit.

Thanks.

**Comment by simojenki** [comment]
It's currently not built for arm
V6, however in theory that could be fixed relatively easily, however;

Sonos inc. have released a new version of their app that breaks bonob

**Comment by pinknoise** [comment]
Yes, I thought I was safe from the Sonos shambles as I'm still on the S1 app but I had to rebuild my server and then couldn't reconnect to my music library. Samba issues I believe. I've installed Navidrome and since posting here discovered that Symfonium can play out to my Sonos speaker. So, all good for now, I can access my music again!

It's quite shocking what Sonos have done tbh and sorry they've wrecked your project among the million other issues they've caused.

If it ever gets fixed I could raise this again as a feature request maybe. Thanks for your response.

**Comment by simojenki** [comment]
I looked into supporting armv6, that requires a bit of work as I would need to change from using a debian base image back to the alpine base image, as node do not publish a debian armv6 image.
https://hub.docker.com/r/arm32v6/node/

**Comment by pinknoise** [comment]
Thanks for taking look. I'll look into a redundant android tv device I have to see if that is more up to date as I think I'll be running in to this problem again. Portainer also out of bounds for now.

Best of luck with the Sonos issues. Cheers, I'll close thread now.
