### ISSUE TITLE
Icon for each "folder"

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#21]
Hi,

Now all the "folders" like artists, albums, playlists, etc. have the same folder like icon.
Is it possible to given them their own icons/image?

For "started" (/favorites) I would expect a, commonly used, start icon, etc., etc.
I came up with the thought after seeing the icons in the music library of the sonos app.

No idea if this is an option, but it would be nice to have a dedicated item for each option.
In that way you can navigation on icons without reading all the text :)

**Comment by simojenki** [comment]
sonos supports icons for those 'folders', the MixCloud app has simple icons.

Someone would need to make icons, or perhaps there are some suitable open source icons available?

**Comment by jicho** [comment]
What do you think of this (partly based on Navidrome):

![A4](https://user-images.githubusercontent.com/610740/129472528-a4615e38-3adc-47a2-8736-df8a4626b409.png)

The icons are mostly created/copied from:
https://www.vectornator.io/icons

They are free to use, this is how they say it on their site:
```
And don’t worry! When you use one of our icons, you won’t have to think about paying for it, obtaining a license, or crediting anyone.
All of our icons are completely free to use in all your designs, forever. You’ll never need another icon finder again. 
```

In case you like this set of icons:
* it would be nice to give them some credits in the readme
* let me know in which dimensions you need them
* and... do you need them with a transparant background, or... with the gray background?

**Comment by simojenki** [comment]
Oh, they look good.  Thanks!

Let's start with transparent background in the default image size they provide, bonob already does image resizing so it can resize these on the fly also.  We can change it later if we need to optimise.

**Comment by simojenki** [comment]
Looks like we need png with transparent background, and also svg of the icons.  
See -> https://developer.sonos.com/build/content-service-add-features/add-images/  
section: Image substitution and custom browse icons

**Comment by jicho** [comment]
LOL, I've also found that page :)

And... you're almost correct, based on this page we need a background also:
https://developer.sonos.com/build/content-service-add-features/add-images/add-browse-icons/

The background color is probably something you can also add when I give the hex-color-code?
I can, of course, also add them to the images/svg

**Comment by simojenki** [comment]
I tested it with transparent backgrounds on ios.

![image](https://user-images.githubusercontent.com/4586/129549013-8701029a-b01b-4d90-b91b-f963e9cfdee6.png)

**Comment by simojenki** [comment]
Perhaps if we use transparent, we can apply the background on fly to match the navidrome users theme?

**Comment by jicho** [comment]
That really doesn't look bad!
I will try to create the svg/png images later today, but I will make them a bit smaller within the dimensions that we have.
A little smaller isn't so into your face.

Regarding the background based on Navidrome, that sound like an idea.
I guess that the navigation bar (background) color is the one to get.
When you do that you should also change the icon color based on the navigation bar. Else you can end with a black icon on a black bar ;) That sounds like auto-switching between a white and black icon color based on the background.

And... what to do with the people who don't want to use the Navidrome theme?
Here is someone that doesn't want to use Navidrome, most of the times I like the default app colors the most. In this case the Sonos app. Reason? Most of the time it just looks the best in the whole picture.

But... I must admit, I do like the idea.

**Comment by simojenki** [comment]
Agree, I think the background color in blue would look a bit odd.  The icon itself might look better however.

**Comment by jicho** [comment]
That can be an idea, but what happens with the "Dark" theme?
The lighter blue will be difficult to see on the grayish background of the Sonos App.
And what about the background color of the Ligera theme? That will make the icon almost disappear...

This almost asks for a Navidrome icon color setting that bonob can use, or...  one in bonob. Although bonob has no custom settings at the moment. And you probably don't want them?

I would welcome custom settings, even for the menu options/filters. For the usage in Sonos not all Navidrome sorting is logical in my eyes at least. But... that's a different discussion so I do not start that here ;)

**Comment by simojenki** [comment]
Lets just go with block icon for now, we can always make it look fancy with colors later.

**Comment by jicho** [comment]
Can you try with the files in the .zip?
 [Archief.zip](https://github.com/simojenki/bonob/files/6993370/Archief.zip)

I'm not 100% sure Sonos is accepting the svg-files ince there are some nodes and attributes that are added by the illustration tool and are not part of the SVG1.1-W3C guidelines.

I hope that Sonos isn't complaining about them.
Everything looks fine in my browser, so they have nothing to do with the svg rendering 🤞 

When it doesn't work there is probably a python script or something to remove those data ;)

Oh... all images are 512 x 512 pixels and the icons are aligned horizontally and vertically in the square so we might need to reposition the "mostly" and "recently" icons, but... first let's see what happens when everything is aligned the same way.

**Comment by jicho** [comment]
Based on #22 I've created a new set of icons.

The "Starred" in the English translation is officially the "Favorites" when you look at Navidrome.
And the "Starred" is missing.

So in the zip ([Archief 2.zip](https://github.com/simojenki/bonob/files/7002608/Archief.2.zip)) you'll find all the existing icons and a new one.
At the end "Starred" ("Top rated" in Navidrome) has the "starred.png/.svg" images and "Favorites" have the corresponding .png/.svg

Have fun!

**Comment by simojenki** [comment]
I took a slightly different approach, I copied the svgs from navidrome and got bonob to resize those on the fly to suit sonos.  Try it out and let me know what you think?

**Comment by jicho** [comment]
Smart idea!

I must admit that I like the grayish background and (a little rounded) white icons more, but that probably a personal thing.
Advantage of the current way of working is the link/match with Navidrome!

There is one thing, in my opinion, that you should change... Match the icon dimensions to the Sonos guidelines. When you don't do that the icons are really into your face (way to large).

The max width/height of the icon is the witdh of the image divided by 2.
So... when the image is 250 pixels, the icon itself should be placed in the center (horizontally and vertically) with a dimension of 125 pixels.

When you do that it should look better.

**Comment by jicho** [comment]
Just tried again, but I'm not seeing any reds font colors with in genres, actually... I don't see any genres ;)
That's probably due to #36

**Comment by jicho** [comment]
After fixing #36 (including getting genres back again from Navidrome) I see the test (yeah).

The the only problem now:
* The text is larges than the icons so most part isn't readable
* The icons (not all) seems larger that the Sonos guidelines describe (max icon width is container/2). An example are the classical and rock icon

Besides that, the text color works 👍

**Comment by jicho** [comment]
Maybe it's a good think to mention in the readme that ```BONOB_ICON_FONT_COLOR ``` is only for the genre icons.

Oh... How can I disable the text display on the genre icons?
I do like the idea, but text over icons and having the same text next to the icons.
For me it is a little over the top:

<img width="414" alt="Schermafbeelding 2021-08-29 om 08 47 47" src="https://user-images.githubusercontent.com/610740/131241414-7e29eaaa-5cb2-436e-af41-b2124dd9dd5b.png">


Only seeing icons would do it for me.

**Comment by simojenki** [comment]
Trouble with the text is that the length is non-deterministic, the sonos app will not resize the text to fit (although for your case above "Amerikaanse traditionele rock" it would have compressed into ineligible text anyway. 

So the only way to have text is to accept that it will have to overflow off the icon it would seem.

There is currently no-way to disable the text.

**Comment by jicho** [comment]
Hmm, okay. That sounds that the text trouble is caused by Sonos API/logic, right?

What I do not understand is that Sonos itself has a completely different genres view:
<img width="414" alt="Schermafbeelding 2021-08-29 om 10 50 57" src="https://user-images.githubusercontent.com/610740/131244738-851f8806-c331-46c1-9ea2-ec5b4bdb2c2c.png">

That's probably a view setting? One that isn't implemented nicely since it just stops displaying long text ;)

**Comment by simojenki** [comment]
The text scaling i *think* is a limitation is the rendering engine the sonos app is using for the svg graphics.  Works ok in desktop browser, but I guess the icon is much bigger there.  I think I'll just remove the text entirely.  Not entirely sure why the icons dont scale properly, will require further analysis.

Sonos I guess customised the view to give it the A,B,C on the left.  The #,A,B,C.... on the right presumably appears when scroll indices are enabled.

**Comment by simojenki** [comment]
I've removed the text, and fixed a few of the icons where the sizing was incorrect.  Looks pretty good now, try it out.

**Comment by jicho** [comment]
Yes, indeed, it looks nice!
A "go" from this side ;)

You might consider adding the attached ([Archief.zip](https://github.com/simojenki/bonob/files/7081487/Archief.zip)) files in genres for:

* Christmas (or "Kerst" in Dutch) / Holidays
  Christmas-Tree-66793.svg
* Spoken & Audio
  Audio-Wave-1892.svg
* Comedie (or "Komedie" in Dutch)
  Theatre-Mask-111172.svg
* Christian / Religious 
  Chapel-69791.svg

There are probably more icons wanted/needed, but this is what I can come up so far.
And... it looks like this needs some multi lingual support :)

I must admit... I have no clue if there is an official genres list...

**Comment by simojenki** [comment]
I will add those additional icons in the coming days.

There is a list of 'official' genres in the ID3 spec -> https://en.wikipedia.org/wiki/List_of_ID3v1_Genres

Though what is in a file could be anything.

bonob will take a guess, ie.  "Classic Rock" & "Rock" & "Alternative Rock" all contain "Rock", so they will get the rock icon..  

As for multilingual, I guess it would need a translation of the genres in the ID3 spec?  Maybe those are available online somewhere?

**Comment by jicho** [comment]
Thanks for the list!
I just tried to find an official translation list of the genres, can't find it...

When I switch my Synology NAS between languages, Audio station is always giving English genres.
The only place when I see, in my case, Dutch options for genres is in iTunes/Music App... And even in iTunes it is a mix of English and Dutch...

I'm not 100% sure, but it looks like genres are on most places in English.
I can, of course, translate them although I'm not sure I know all the official translations.

What do you think? Leave them in English and see what the future brings or... translate them as good as possible and update when someone has a better translation.

**Comment by simojenki** [comment]
I think for now leave them as English.

**Comment by simojenki** [comment]
I've added the additional icons and mappings that you provided in the previous comment.  Give it a go and let me know how it goes?

**Comment by jicho** [comment]
The new icons are working.
The christmas icon is the only one that looks a bit odd within the rest of the les. All icons are "fat"/bold, this one isn't...
It's a bit the same with the "rock" icon (guitar).

On of the following might look better:
[Archief.zip](https://github.com/simojenki/bonob/files/7109334/Archief.zip)

Although I think the Christmas tree might needs some roundings at the end?

The icons are (as always) from www.vectornator.io/icons

**Comment by simojenki** [comment]
I applied a tree and guitar from the zip, Try those.

**Comment by jicho** [comment]
In my opinion this looks much better between the other icons.
They don't stand out anymore.
