### ISSUE TITLE
Sonos Registration Issue

### ISSUE THREAD

**Issue by daNutzzzzz** [simojenki/bonob#210]
Hi,

I was using Bonob a while back and recently came to play some music and found it no longer working.

When i check the logs i can see its configured correctly to register with one of the sonos devices (10.0.95.15) but for some reason bonob is trying to register with the sonos bridge (10.0.95.5):

`INF INF INF INF Starting bonob with config {"port":4534,"bonobUrl":{"url":"http://10.0.9.41:4534/"},"secret":"*******","authTimeout":"1h","icons":{},"logRequests":false,"sonos":{"serviceName":"HomeMusic","discovery":{"enabled":true,"seedHost":"10.0.95.15"},"autoRegister":true,"sid":246},"subsonic":{"url":{"url":"http://navidrome:4533/"}},"scrobbleTracks":true,"reportNowPlaying":true} | INF INF INF INF Starting bonob with config {"port":4534,"bonobUrl":{"url":"http://10.0.9.41:4534/"},"secret":"*******","authTimeout":"1h","icons":{},"logRequests":false,"sonos":{"serviceName":"HomeMusic","discovery":{"enabled":true,"seedHost":"10.0.95.15"},"autoRegister":true,"sid":246},"subsonic":{"url":{"url":"http://navidrome:4533/"}},"scrobbleTracks":true,"reportNowPlaying":true} | service=bonob INF INF INF INF Starting bonob with config {"port":4534,"bonobUrl":{"url":"http://10.0.9.41:4534/"},"secret":"*******","authTimeout":"1h","icons":{},"logRequests":false,"sonos":{"serviceName":"HomeMusic","discovery":{"enabled":true,"seedHost":"10.0.95.15"},"autoRegister":true,"sid":246},"subsonic":{"url":{"url":"http://navidrome:4533/"}},"scrobbleTracks":true,"reportNowPlaying":true} | INF INF INF INF Starting bonob with config {"port":4534,"bonobUrl":{"url":"http://10.0.9.41:4534/"},"secret":"*******","authTimeout":"1h","icons":{},"logRequests":false,"sonos":{"serviceName":"HomeMusic","discovery":{"enabled":true,"seedHost":"10.0.95.15"},"autoRegister":true,"sid":246},"subsonic":{"url":{"url":"http://navidrome:4533/"}},"scrobbleTracks":true,"reportNowPlaying":true} | service=bonob timestamp=2024-11-21 19:52:48
INF INF INF INF Trying to discover sonos devices using seed 10.0.95.15 | INF INF INF INF Trying to discover sonos devices using seed 10.0.95.15 | service=bonob INF INF INF INF Trying to discover sonos devices using seed 10.0.95.15 | INF INF INF INF Trying to discover sonos devices using seed 10.0.95.15 | service=bonob timestamp=2024-11-21 19:52:48
INF INF INF INF Listening on 4534 available @ http://10.0.9.41:4534/ | INF INF INF INF Listening on 4534 available @ http://10.0.9.41:4534/ | service=bonob INF INF INF INF Listening on 4534 available @ http://10.0.9.41:4534/ | INF INF INF INF Listening on 4534 available @ http://10.0.9.41:4534/ | service=bonob timestamp=2024-11-21 19:52:48
INF INF INF INF register using sonos device BRIDGE @ 10.0.95.5 | INF INF INF INF register using sonos device BRIDGE @ 10.0.95.5 | service=bonob INF INF INF INF register using sonos device BRIDGE @ 10.0.95.5 | INF INF INF INF register using sonos device BRIDGE @ 10.0.95.5 | service=bonob timestamp=2024-11-21 19:52:49`

Any idea how to fix this?

**Comment by simojenki** [comment]
what happens if you power off the bridge and then re-try the registration, and then power it back on again?  
Alternatively try setting a static IP for the bridge in your routers DHCP config, where the IP address has a value greater than that of one of the speakers?

I suspect what is happening is that bonob is using the seed host you provided to discover the sonos network, it then uses the first device in the list of discovered devices in order to register, in your case it has found the bridge, which it would seem does not allow registering services with.  

I don't use a bridge, so I cannot verify that, however the above may work around the issue for the time being.  I 'proper' fix is to differentiate between speakers and bridges (or boosts i guess)

**Comment by daNutzzzzz** [comment]
> what happens if you power off the bridge and then re-try the registration, and then power it back on again? Alternatively try setting a static IP for the bridge in your routers DHCP config, where the IP address has a value greater than that of one of the speakers?
> 
> I suspect what is happening is that bonob is using the seed host you provided to discover the sonos network, it then uses the first device in the list of discovered devices in order to register, in your case it has found the bridge, which it would seem does not allow registering services with.
> 
> I don't use a bridge, so I cannot verify that, however the above may work around the issue for the time being. I 'proper' fix is to differentiate between speakers and bridges (or boosts i guess)

thanks for the replay and suggestion. Im happy to say this worked as it registered against the seed host correctly once i put the host in a higher IP. I still dont understand why this would be as one would assume the seed host is the host its told to register against and not search. And that it worked previously.. all my Sonos devices are already statically assigned and nothings changed.

**Comment by simojenki** [comment]
The seed host is a seed to discover the sonos devices, as auto discovery may not work in all cases.  ie. sonos devices are on a different VLAN.
Once the sonos devices are discovered bonob currently just uses the first device in the list of devices, not necessarily the seed device.  Perhaps this could be improved.
Why did it change in your case, I'm not sure, the ordering of the devices is not something bonob currently does, so the order given to it from the library i use to discover sonos devices is the order it uses, perhaps something changed in that library, or in the sonos devices themselves that affected to ordering...  Either way, could probably explicitly filter that list to remove bridge/boost devices for registration.

**Comment by daNutzzzzz** [comment]
Ah ok that makes sense and yes implementing a filter to ignore bridge/boost would be a good addition :)
