### ISSUE TITLE
Not all albums visible in albums list/overview

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#24]
Hi,

When you look at the albums overview it stopt after seeing 100 covers.
When you do the same with the SMB connection of the Sonos App you can see all covers, in my case 251.

How can I see all covers in the albums list? It now just stops :(

And I know why I could find an album by scrolling ;)

**Comment by simojenki** [comment]
The issue is that the subsonic album api endpoint only supports 500 anyway.
http://www.subsonic.org/pages/api.jsp#getAlbumList
So to fix that properly I would need to use a different API in navidrome that supports paging albums

**Comment by jicho** [comment]
The 500 limit sounds logical, although getAlbumList supports paging.
But... you probably want to think about the logic in the Sonos App also.

It seems kind of weird to see a list of x-albums and at the last entry is a "go to next page/list" album :)

**Comment by simojenki** [comment]
I think the 100 limit is because the "Albums" list is of type "albumList"

```
An albumList container is a list of albums by different artists. The Sonos app displays items in albumList containers with the name of the artist below the name of the album. You might use an albumList container to present a list of Top 100 Albums or New Releases.
```

Perhaps if it was a simple collection then paging would work properly.  The scrollIndicies would make it actually usable.

**Comment by jicho** [comment]
It looks like SMAPI has paging logic on board:
https://developer.sonos.com/build/content-service-add-features/add-pagination/

That in combination with get getAlbumList option of subsonic:
http://www.subsonic.org/pages/api.jsp#getAlbumList

Should solve the long list problem.

That's probably easier said than done...

**Comment by simojenki** [comment]
Yes that would fix it.  In fact it already implemented in that way, however the total does not seem to be available via the subsonic api, so bonob is currently reporting the total as the number of entries on the first page, causing the sonos app to not bother asking for page 2.

**Comment by jicho** [comment]
Maybe it is an idea to do a while loop once a day/hours/something to count the total albums based on the getAlbumList and register that somewhere. The total counts sounds something that's is needed/can be used all over the place.

And yes... it is a bit ugly solution, but... when you need it is and subsonic isn't providing it... Although it is kind of weird that there is no option to get the total number of albums. I would assume that subsonic needs it for paging also...

**Comment by simojenki** [comment]
I think I have a work around for this that seems to work for me.   Try the latest 'master' build and see if it fixes your issue,

**Comment by jicho** [comment]
This fixes also solves the problem with my list, I can see all the albums now!

When you would ask me... Case closed.
