### ISSUE TITLE
Display version number on bonob page

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#28]
Hi,

Is it an idea to display the bonob version number on the registration page (http://bonob:4534)?
This info can be handy when you want to figure out whether you're running the latest version or not...

**Comment by simojenki** [comment]
Until yesterday there was only 1 version, 'latest'.  I tagged a release of 0.1.0, so I'll keep this in mind

**Comment by jicho** [comment]
okay, thanks!

**Comment by simojenki** [comment]
This should be fixed on the / route.

**Comment by jicho** [comment]
Yes, this one is fixed. Found it on the top right corner.
Nice and thanks!
