### ISSUE TITLE
No genres in Sonos Controller on Mac and in App

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#36]
When I go to genres on the Sonos Controller on a Mac the list stays empty...

The request according to the log:
```
{"message":"Fetching metadata type=genres, typeId=undefined, acceptLanguage=nl-NL, en-US;q=0.9","level":"debug","service":"bonob","timestamp":"2021-08-28 08:30:00"}
```

The response according to the log:
```
{"message":{"level":"debug","data":"<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"  xmlns:tns=\"http://www.sonos.com/Services/1.1\"><soap:Body><soap:Fault><soap:Code><soap:Value>SOAP-ENV:Server</soap:Value><soap:Subcode><soap:value>InternalServerError</soap:value></soap:Subcode></soap:Code><soap:Reason><soap:Text>TypeError: Cannot read property &apos;map&apos; of undefined</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>"},"level":"debug","service":"bonob","timestamp":"2021-08-28 08:30:00"}
```

I have this issue on the "master" in combination with:
```
    -e BONOB_ICON_FONT_COLOR=red \
    -e BONOB_ICON_FONT_FAMILY=Arial \
```

**Comment by simojenki** [comment]
It looks like you have no genres?  I've pushed a fix for the error which occurred when there were no genres.  
Now however I suspect that you will just get an empty list.

**Comment by jicho** [comment]
Hmm... the error is gone, so that's a good thing.

I think I understand why I'm not getting any genres in the Sonos App... The Navidrome rest-api isn't giving any back:
```
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.16.1" type="navidrome" serverVersion="0.45.1 (c55e6590)">
<genres/>
</subsonic-response>
```
Long story short... After the upgrade tot Navidrome 1.45.0/1.45.1 Navidrome didn't return any genres in the rest API...
After a re-index they where back in the rest API and in the App.
