### ISSUE TITLE
Internal server error with "browse by this artist"

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#46]
Hi,

Do you have any idea why I get an internal server error in bonob when I choose "browse by this artist"? I'm not having the official English translation for this, but you can access the "page" in the Sonos iOS App by:
* Go to album
* Press ...
* Choose "more"
* Choose "browse by this artist"
* Sonos App is giving the error that I can't browse the music

The following is happening in the bonob logs:
```

{"message":{"level":"info","data":"Trying SonosSoap from path /Test/TestService.php"},"level":"info","service":"bonob","timestamp":"2021-09-06 21:25:09"}

{"message":"Fetching metadata type=054778610ba1de6f0c973a4571dc3fe4, typeId=undefined, acceptLanguage=nl-NL, en-US;q=0.9","level":"debug","service":"bonob","timestamp":"2021-09-06 21:25:09"}

{"message":{"level":"debug","data":"<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"  xmlns:tns=\"http://www.sonos.com/Services/1.1\"><soap:Body><soap:Fault><soap:Code><soap:Value>SOAP-ENV:Server</soap:Value><soap:Subcode><soap:value>InternalServerError</soap:value></soap:Subcode></soap:Code><soap:Reason><soap:Text>Unsupported getMetadata id=054778610ba1de6f0c973a4571dc3fe4</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>"},"level":"debug","service":"bonob","timestamp":"2021-09-06 21:25:09"}
```

I'm using the master at the moment, the one with the new icons ;)

**Comment by simojenki** [comment]
Looks like a minor bug in the way bonob tells the sonos controller what to do;

The id in this string 'Unsupported getMetadata id=054778610ba1de6f0c973a4571dc3fe4' doesn't look correct, it probably should be prefixed with 'artist:' ie. 'artist:054778610ba1de6f0c973a4571dc3fe4'.  

I'll take a look

**Comment by simojenki** [comment]
This should be fixed in master image.

**Comment by jicho** [comment]
I can confirm that it works now, thanks!
