### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#50]
Hi,

Since this morning I'm the Sonos app isn't getting data from bonob...
I've tried to register the Sonos app to bonob, but when I do that I get the error:
```Error: getaddrinfo EAI_AGAIN```

This is happening with the master and the latest.

Nothing has changed since yesterday... Do you have any idea where to look for a solution?

This is the error in the bonob logs:
```
{"message":{"level":"debug","data":"<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"  xmlns:tns=\"http://www.sonos.com/Services/1.1\"><soap:Body><soap:Fault><soap:Code><soap:Value>SOAP-ENV:Server</soap:Value><soap:Subcode><soap:value>InternalServerError</soap:value></soap:Subcode></soap:Code><soap:Reason><soap:Text>Error: getaddrinfo EAI_AGAIN nas***********</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>"},"level":"debug","service":"bonob","timestamp":"2021-09-09 07:47:48"}
```

There is a second bonob account in the Sonos App, that can't show albums either, but it does display the main menu. I assume that is coming from bonob also.

As soon as I'm trying to get albums I m'n not getting anything, but I do get this in the logs:
```

{"message":{"level":"info","data":"Handling POST on /ws/sonos"},"level":"info","service":"bonob","timestamp":"2021-09-09 07:58:46"}

{"message":{"level":"debug","data":"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Header><credentials xmlns=\"http://www.sonos.com/Services/1.1\"><loginToken><token>***********</token><householdId>Sonos_4CK********************lR</householdId></loginToken><deviceId>78-*******:E</deviceId><deviceProvider>Sonos</deviceProvider></credentials></s:Header><s:Body><getMetadata xmlns=\"http://www.sonos.com/Services/1.1\"><id>albums</id><index>0</index><count>100</count></getMetadata></s:Body></s:Envelope>"},"level":"debug","service":"bonob","timestamp":"2021-09-09 07:58:46"}

{"message":{"level":"info","data":"Attempting to bind to /ws/sonos"},"level":"info","service":"bonob","timestamp":"2021-09-09 07:58:46"}

{"message":{"level":"info","data":"Trying SonosSoap from path /Test/TestService.php"},"level":"info","service":"bonob","timestamp":"2021-09-09 07:58:46"}

{"message":"Fetching metadata type=albums, typeId=undefined, acceptLanguage=nl-NL, en-US;q=0.9","level":"debug","service":"bonob","timestamp":"2021-09-09 07:58:46"}

{"message":{"level":"debug","data":"<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"  xmlns:tns=\"http://www.sonos.com/Services/1.1\"><soap:Body><soap:Fault><soap:Code><soap:Value>SOAP-ENV:Server</soap:Value><soap:Subcode><soap:value>InternalServerError</soap:value></soap:Subcode></soap:Code><soap:Reason><soap:Text>Error: getaddrinfo EAI_AGAIN nas***********</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>"},"level":"debug","service":"bonob","timestamp":"2021-09-09 07:58:51"}

::ffff:192.168.11.20 - - [09/Sep/2021:05:58:51 +0000] "POST /ws/sonos HTTP/1.1" 500 - "-" "Linux UPnP/1.0 Sonos/64.3-20120 (ICRU_iPhone12,1)"

```

Thanks!

**Comment by simojenki** [comment]
I've never seen that before.  

EAI_AGAIN sounds like a DNS lookup failure.

Could it be that your docker containers cannot resolve the DNS entry you have for navidrome?

**Comment by jicho** [comment]
It looks like it, when I do a ping to ```nas*******``` from inside the container I don't get a reply.
When I do to the same name in my browser I do get a response/result.

For some reason this is happening over night, how odd... I'm still using the ```--network host``` setting.

When I add my internal router "domain" to the ping I get a response from inside the container...

I will try to manually set the container DNS, just learned that this is possible with --dns.

The very strange thing in this all is that the current DNS set in ```/etc/resolv.conf``` is the same as all over the place :S

Oh well... I will figure it out later today. 
Thanks for thinking with me. 
Will update the issue when I have more info!

**Comment by jicho** [comment]
I've solved it differently!

After adding:
```-e BONOB_NAVIDROME_URL=http://192.168.xx.xxx:4533```

bonob is playing music again ;)

Sometimes the easy solution is the best one!
