### ISSUE TITLE
Place Config outside docker container

### ISSUE THREAD

**Issue by gitknd** [simojenki/bonob#60]
Hi,
great job so far (missing folder view so far). 
Which folder must i map to place the config outside the docker container (i normally re-create my container with the latest image with Portainer).
thanks
K.

**Comment by simojenki** [comment]
Config is via ENV vars, so lives in your portainer UI (or whatever you use to manage your containers), there is no config directory as such.

Folder view?  Is that not made redundant by the use of tags in the files themselves?

**Comment by gitknd** [comment]
folder view is not redundant, it's another way to navigate through a large sorted collection. I mostly used this way with the native sonos implementation.

**Comment by simojenki** [comment]
Closing this issue as config is already externalised as ENV vars as per 12 factor app principles.  'Folder view' is a different issue, at this point Navidrome does not support 'folder view' so there is no urgency in bonob doing so.
