### ISSUE TITLE
Observations on performance of rating interface

### ISSUE THREAD

**Issue by dbuttric** [simojenki/bonob#64]
The rating interface works better than I had imagined.
Thank you!
I have some performance observations to share, that might influence future work.
In my environment, from the Sonos Controller it takes a few seconds between when I press the star, and the rating is updated on the controller. It seems like there is quite a bit of latency somewhere.

This is in contrast to the Sonos Widget on Android, which seems to update the rating immediately, and the rating operation feels much more interactive.

I cannot account for the differences in behavior between the sonos controller, and the sonos widget, but they are worth noting.

Someday, I'm going to figure out how to host a node app for development, and then I'll be able to give you much better diagnostic information.

**Comment by simojenki** [comment]
How has your testing of this gone?

**Comment by simojenki** [comment]
As I've not heard any update on this issue and the ratings buttons seem to work ok for me, so I am closing this issue.
