### ISSUE TITLE
Bonob crash during playback

### ISSUE THREAD

**Issue by jicho** [simojenki/bonob#70]
Hi,

The Bonob container just restarted with this error in the log:

![image](https://user-images.githubusercontent.com/610740/140076709-b9ba2ba1-525c-4c9d-8005-354b9f46381e.png)

Synology is exporting the logs from new to old, so... at the bottom you can see the start of the error ;)

Do you have any idea what could have caused this?

**Comment by simojenki** [comment]
At the time it crashed were you browsing/scrolling through the artists list?

**Comment by jicho** [comment]
Nope, I was just listening to a song. The song was, when I heard correctly, almost finished (not 100% sure) and at that moment everything stopped.

**Comment by jicho** [comment]
I will close this issue, since the last "latest" release this error seems to be history.
