### ISSUE TITLE
Question about basic usage on how to play music continuously

### ISSUE THREAD

**Issue by garret** [simojenki/bonob#90]
I managed to set up bonob (on a raspberry pi thanks to the developer and using navidrome as subsonic interface) however I only have one last issue that maybe it is just me I don't get it right. Most of my tracks are single tracks taken from an album, so it happens that for instance when I go to play a song from the folder "Recently added" or "Random" I would like that all the songs from that folder are played automatically but instead only one song is played and then there is no possibility to go to the next one unless I manually select it and click play. As I understand, this happens because bonob only plays the song of the album. If that album had 2 tracks, then the next track would be played and no more. 

I attach a screenshot of what I mean to hopefully be more clear. Down below there is the "Most played" folder. 

![Screenshot_20211225-172113](https://user-images.githubusercontent.com/27555/147389461-9226c7c2-7805-4457-9fb6-d4b217070274.png)

I would like to have the possibility to reproduce all the tracks in this folder (and maybe choose if I want them shuffled and/or repeated), while at the moment it seems I can only click on the specific album and then only the tracks of that album are streamed.

**Comment by simojenki** [comment]
bonob doesn’t currently support ‘folder view’, partly because neither does Navidrome.

‘Recently Added’ & ‘Random’ are both ‘album views’.

Navidrome lends itself well to having music organised by Albums with the album data in the ID3 tags.

Depending on the size of your collection, you could try using m3u playlist files and having Navidrome import them?

**Comment by garret** [comment]
Thank you, I guess I will have to find a way to automatically create a playlist somehow with the content of my folder and find a way to import it. It seems it is not a limitation of bonob but of Navidrome so I will close the issue. Thank you again for the fast support!
