### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by eddipedersen** [simojenki/bonob#91]
Got a Nanopim4 server running navidrome in docker and i got some sonos speakers as well...
But im so sad that your implimentatio of navidrome and sonos don´t run on ARM device..
is it posibel to code it for ARM as well :-) i know a lot of people would be so glad.

**Comment by simojenki** [comment]
I've added arm64 platform support to version 0.6.1 (latest at time of writing), try that for the Nanopim4.

**Comment by eddipedersen** [comment]
Million thanks for your time and effort it worked... Happy New Year...
Eddi

**Comment by simojenki** [comment]
resolved
